var countryCodes = {
	"bd": "Bangladesh",
	"be": "Belgium",
	"bf": "Burkina Faso",
	"bg": "Bulgaria",
	"ba": "Bosnia and Herzegovina",
	"bb": "Barbados",
	"wf": "Wallis and Futuna",
	"bl": "Saint Barthelemy",
	"bm": "Bermuda",
	"bn": "Brunei",
	"bo": "Bolivia",
	"bh": "Bahrain",
	"bi": "Burundi",
	"bj": "Benin",
	"bt": "Bhutan",
	"jm": "Jamaica",
	"bv": "Bouvet Island",
	"bw": "Botswana",
	"ws": "Samoa",
	"bq": "Bonaire, Saint Eustatius and Saba",
	"br": "Brazil",
	"bs": "Bahamas",
	"je": "Jersey",
	"by": "Belarus",
	"bz": "Belize",
	"ru": "Russia",
	"rw": "Rwanda",
	"rs": "Serbia",
	"tl": "East Timor",
	"re": "Reunion",
	"tm": "Turkmenistan",
	"tj": "Tajikistan",
	"ro": "Romania",
	"tk": "Tokelau",
	"gw": "Guinea-Bissau",
	"gu": "Guam",
	"gt": "Guatemala",
	"gs": "South Georgia and the South Sandwich Islands",
	"gr": "Greece",
	"gq": "Equatorial Guinea",
	"gp": "Guadeloupe",
	"jp": "Japan",
	"gy": "Guyana",
	"gg": "Guernsey",
	"gf": "French Guiana",
	"ge": "Georgia",
	"gd": "Grenada",
	"gb": "United Kingdom",
	"ga": "Gabon",
	"sv": "El Salvador",
	"gn": "Guinea",
	"gm": "Gambia",
	"gl": "Greenland",
	"gi": "Gibraltar",
	"gh": "Ghana",
	"om": "Oman",
	"tn": "Tunisia",
	"jo": "Jordan",
	"hr": "Croatia",
	"ht": "Haiti",
	"hu": "Hungary",
	"hk": "Hong Kong",
	"hn": "Honduras",
	"hm": "Heard Island and McDonald Islands",
	"ve": "Venezuela",
	"pr": "Puerto Rico",
	"ps": "Palestinian Territory",
	"pw": "Palau",
	"pt": "Portugal",
	"sj": "Svalbard and Jan Mayen",
	"py": "Paraguay",
	"iq": "Iraq",
	"pa": "Panama",
	"pf": "French Polynesia",
	"pg": "Papua New Guinea",
	"pe": "Peru",
	"pk": "Pakistan",
	"ph": "Philippines",
	"pn": "Pitcairn",
	"pl": "Poland",
	"pm": "Saint Pierre and Miquelon",
	"zm": "Zambia",
	"eh": "Western Sahara",
	"ee": "Estonia",
	"eg": "Egypt",
	"za": "South Africa",
	"ec": "Ecuador",
	"it": "Italy",
	"vn": "Vietnam",
	"sb": "Solomon Islands",
	"et": "Ethiopia",
	"so": "Somalia",
	"zw": "Zimbabwe",
	"sa": "Saudi Arabia",
	"es": "Spain",
	"er": "Eritrea",
	"me": "Montenegro",
	"md": "Moldova",
	"mg": "Madagascar",
	"mf": "Saint Martin",
	"ma": "Morocco",
	"mc": "Monaco",
	"uz": "Uzbekistan",
	"mm": "Myanmar",
	"ml": "Mali",
	"mo": "Macao",
	"mn": "Mongolia",
	"mh": "Marshall Islands",
	"mk": "Macedonia",
	"mu": "Mauritius",
	"mt": "Malta",
	"mw": "Malawi",
	"mv": "Maldives",
	"mq": "Martinique",
	"mp": "Northern Mariana Islands",
	"ms": "Montserrat",
	"mr": "Mauritania",
	"im": "Isle of Man",
	"ug": "Uganda",
	"tz": "Tanzania",
	"my": "Malaysia",
	"mx": "Mexico",
	"il": "Israel",
	"fr": "France",
	"io": "British Indian Ocean Territory",
	"sh": "Saint Helena",
	"fi": "Finland",
	"fj": "Fiji",
	"fk": "Falkland Islands",
	"fm": "Micronesia",
	"fo": "Faroe Islands",
	"ni": "Nicaragua",
	"nl": "Netherlands",
	"no": "Norway",
	"na": "Namibia",
	"vu": "Vanuatu",
	"nc": "New Caledonia",
	"ne": "Niger",
	"nf": "Norfolk Island",
	"ng": "Nigeria",
	"nz": "New Zealand",
	"np": "Nepal",
	"nr": "Nauru",
	"nu": "Niue",
	"ck": "Cook Islands",
	"xk": "Kosovo",
	"ci": "Ivory Coast",
	"ch": "Switzerland",
	"co": "Colombia",
	"cn": "China",
	"cm": "Cameroon",
	"cl": "Chile",
	"cc": "Cocos Islands",
	"ca": "Canada",
	"cg": "Republic of the Congo",
	"cf": "Central African Republic",
	"cd": "Democratic Republic of the Congo",
	"cz": "Czech Republic",
	"cy": "Cyprus",
	"cx": "Christmas Island",
	"cr": "Costa Rica",
	"cw": "Curacao",
	"cv": "Cape Verde",
	"cu": "Cuba",
	"sz": "Swaziland",
	"sy": "Syria",
	"sx": "Sint Maarten",
	"kg": "Kyrgyzstan",
	"ke": "Kenya",
	"ss": "South Sudan",
	"sr": "Suriname",
	"ki": "Kiribati",
	"kh": "Cambodia",
	"kn": "Saint Kitts and Nevis",
	"km": "Comoros",
	"st": "Sao Tome and Principe",
	"sk": "Slovakia",
	"kr": "South Korea",
	"si": "Slovenia",
	"kp": "North Korea",
	"kw": "Kuwait",
	"sn": "Senegal",
	"sm": "San Marino",
	"sl": "Sierra Leone",
	"sc": "Seychelles",
	"kz": "Kazakhstan",
	"ky": "Cayman Islands",
	"sg": "Singapore",
	"se": "Sweden",
	"sd": "Sudan",
	"do": "Dominican Republic",
	"dm": "Dominica",
	"dj": "Djibouti",
	"dk": "Denmark",
	"vg": "British Virgin Islands",
	"de": "Germany",
	"ye": "Yemen",
	"dz": "Algeria",
	"us": "United States",
	"uy": "Uruguay",
	"yt": "Mayotte",
	"um": "United States Minor Outlying Islands",
	"lb": "Lebanon",
	"lc": "Saint Lucia",
	"la": "Laos",
	"tv": "Tuvalu",
	"tw": "Taiwan",
	"tt": "Trinidad and Tobago",
	"tr": "Turkey",
	"lk": "Sri Lanka",
	"li": "Liechtenstein",
	"lv": "Latvia",
	"to": "Tonga",
	"lt": "Lithuania",
	"lu": "Luxembourg",
	"lr": "Liberia",
	"ls": "Lesotho",
	"th": "Thailand",
	"tf": "French Southern Territories",
	"tg": "Togo",
	"td": "Chad",
	"tc": "Turks and Caicos Islands",
	"ly": "Libya",
	"va": "Vatican",
	"vc": "Saint Vincent and the Grenadines",
	"ae": "United Arab Emirates",
	"ad": "Andorra",
	"ag": "Antigua and Barbuda",
	"af": "Afghanistan",
	"ai": "Anguilla",
	"vi": "U.S. Virgin Islands",
	"is": "Iceland",
	"ir": "Iran",
	"am": "Armenia",
	"al": "Albania",
	"ao": "Angola",
	"aq": "Antarctica",
	"as": "American Samoa",
	"ar": "Argentina",
	"au": "Australia",
	"at": "Austria",
	"aw": "Aruba",
	"in": "India",
	"ax": "Aland Islands",
	"az": "Azerbaijan",
	"ie": "Ireland",
	"id": "Indonesia",
	"ua": "Ukraine",
	"qa": "Qatar",
	"mz": "Mozambique",
	"bd-jp": "バングラデシュ",
	"be-jp": "ベルギー",
	"bf-jp": "ブルキナファソ",
	"bg-jp": "ブルガリア",
	"ba-jp": "ボスニア・ヘルツェゴビナ",
	"bb-jp": "バルバドス",
	"wf-jp": "ウォリス・フツナ",
	"bl-jp": "サン・バルテルミー",
	"bm-jp": "バミューダ",
	"bn-jp": "ブルネイ",
	"bo-jp": "ボリビア",
	"bh-jp": "バーレーン",
	"bi-jp": "ブルンジ",
	"bj-jp": "ベナン",
	"bt-jp": "ブータン",
	"jm-jp": "ジャマイカ",
	"bv-jp": "ブーベ島",
	"bw-jp": "ボツワナ",
	"ws-jp": "サモア",
	"bq-jp": "ボネール、シント・ユースタティウスおよびサバ",
	"br-jp": "ブラジル",
	"bs-jp": "バハマ",
	"je-jp": "ジャージー",
	"by-jp": "ベラルーシ",
	"bz-jp": "ベリーズ",
	"ru-jp": "ロシア",
	"rw-jp": "ルワンダ",
	"rs-jp": "セルビア",
	"tl-jp": "東ティモール",
	"re-jp": "レユニオン",
	"tm-jp": "トルクメニスタン",
	"tj-jp": "タジキスタン",
	"ro-jp": "ルーマニア",
	"tk-jp": "トケラウ",
	"gw-jp": "ギニアビサウ",
	"gu-jp": "グアム",
	"gt-jp": "グアテマラ",
	"gs-jp": "サウスジョージア・サウスサンドウィッチ諸島",
	"gr-jp": "ギリシャ",
	"gq-jp": "赤道ギニア",
	"gp-jp": "グアドループ",
	"jp-jp": "日本",
	"gy-jp": "ガイアナ",
	"gg-jp": "ガーンジー",
	"gf-jp": "フランス領ギアナ",
	"ge-jp": "ジョージア",
	"gd-jp": "グレナダ",
	"gb-jp": "イギリス",
	"ga-jp": "ガボン",
	"sv-jp": "エルサルバドル",
	"gn-jp": "ギニア",
	"gm-jp": "ガンビア",
	"gl-jp": "グリーンランド",
	"gi-jp": "ジブラルタル",
	"gh-jp": "ガーナ",
	"om-jp": "オマーン",
	"tn-jp": "チュニジア",
	"jo-jp": "ヨルダン",
	"hr-jp": "クロアチア",
	"ht-jp": "ハイチ",
	"hu-jp": "ハンガリー",
	"hk-jp": "香港",
	"hn-jp": "ホンジュラス",
	"hm-jp": "ハード島とマクドナルド諸島",
	"ve-jp": "ベネズエラ",
	"pr-jp": "プエルトリコ",
	"ps-jp": "パレスチナ自治区",
	"pw-jp": "パラオ",
	"pt-jp": "ポルトガル",
	"sj-jp": "スヴァールバル諸島およびヤンマイエン島",
	"py-jp": "パラグアイ",
	"iq-jp": "イラク",
	"pa-jp": "パナマ",
	"pf-jp": "フランス領ポリネシア",
	"pg-jp": "パプアニューギニア",
	"pe-jp": "ペルー",
	"pk-jp": "パキスタン",
	"ph-jp": "フィリピン",
	"pn-jp": "ピトケアン",
	"pl-jp": "ポーランド",
	"pm-jp": "サンピエール・ミクロン",
	"zm-jp": "ザンビア",
	"eh-jp": " 西サハラ",
	"ee-jp": " エストニア",
	"eg-jp": " エジプト",
	"za-jp": "南アフリカ",
	"ec-jp": " エクアドル",
	"it-jp": "イタリア",
	"vn-jp": "ベトナム",
	"sb-jp": " ソロモン諸島",
	"et-jp": " エチオピア",
	"so-jp": " ソマリア",
	"zw-jp": "ジンバブエ",
	"sa-jp": "サウジアラビア",
	"es-jp": "スペイン",
	"er-jp": " エリトリア",
	"me-jp": " モンテネグロ",
	"md-jp": " モルドバ",
	"mg-jp": " マダガスカル",
	"mf-jp": " セント・マーチン島",
	"ma-jp": "モロッコ",
	"mc-jp": " モナコ",
	"uz-jp": " ウズベキスタン",
	"mm-jp": " ミャンマー",
	"ml-jp": " マリ",
	"mo-jp": " マカオ",
	"mn-jp": " モンゴル",
	"mh-jp": " マーシャル諸島",
	"mk-jp": "マケドニア",
	"mu-jp": " モーリシャス",
	"mt-jp": " マルタ",
	"mw-jp": " マラウイ",
	"mv-jp": " モルディブ",
	"mq-jp": " マルティニーク",
	"mp-jp": " 北マリアナ諸島",
	"ms-jp": " モンセラート",
	"mr-jp": " モーリタニア",
	"im-jp": " マン島",
	"ug-jp": " ウガンダ",
	"tz-jp": " タンザニア",
	"my-jp": "マレーシア",
	"mx-jp": "メキシコ",
	"il-jp": "イスラエル",
	"fr-jp": "フランス",
	"io-jp": " 英領インド洋領土",
	"sh-jp": " セントヘレナ",
	"fi-jp": "フィンランド",
	"fj-jp": " フィジー",
	"fk-jp": " フォークランド諸島",
	"fm-jp": "ミクロネシア",
	"fo-jp": " フェロー諸島",
	"ni-jp": "ニカラグア",
	"nl-jp": "オランダ",
	"no-jp": "ノルウェー",
	"na-jp": "ナミビア",
	"vu-jp": " バヌアツ",
	"nc-jp": " ニューカレドニア",
	"ne-jp": " ニジェール",
	"nf-jp": " ノーフォーク島",
	"ng-jp": "ナイジェリア",
	"nz-jp": "ニュージーランド",
	"np-jp": " ネパール",
	"nr-jp": " ナウル",
	"nu-jp": " ニウエ",
	"ck-jp": " クック諸島",
	"xk-jp": " コソボ",
	"ci-jp": " コートジボワール",
	"ch-jp": "スイス",
	"co-jp": " コロンビア",
	"cn-jp": "中国",
	"cm-jp": " カメルーン",
	"cl-jp": "チリ",
	"cc-jp": " ココス諸島",
	"ca-jp": "カナダ",
	"cg-jp": " コンゴ共和国",
	"cf-jp": " 中央アフリカ共和国",
	"cd-jp": " コンゴ民主共和国",
	"cz-jp": "チェコ共和国",
	"cy-jp": " キプロス",
	"cx-jp": " クリスマスアイランド",
	"cr-jp": "コスタリカ",
	"cw-jp": "キュラソー",
	"cv-jp": " カーボベルデ",
	"cu-jp": "キューバ",
	"sz-jp": " スワジランド",
	"sy-jp": "シリア",
	"sx-jp": " シントマーティン",
	"kg-jp": " キルギス",
	"ke-jp": " ケニア",
	"ss-jp": " 南スーダン",
	"sr-jp": " スリナム",
	"ki-jp": " キリバス",
	"kh-jp": "カンボジア",
	"kn-jp": " セントクリストファー・ネイビス",
	"km-jp": " コモロ",
	"st-jp": " サントメ・プリンシペ",
	"sk-jp": "スロバキア",
	"kr-jp": " 韓国",
	"si-jp": "スロベニア",
	"kp-jp": "北朝鮮",
	"kw-jp": "クウェート",
	"sn-jp": " セネガル",
	"sm-jp": " サンマリノ",
	"sl-jp": "シエラレオネ",
	"sc-jp": " セイシェル",
	"kz-jp": " カザフスタン",
	"ky-jp": " ケイマン諸島",
	"sg-jp": "シンガポール",
	"se-jp": "スウェーデン",
	"sd-jp": " スーダン",
	"do-jp": "ドミニカ共和国",
	"dm-jp": " ドミニカ",
	"dj-jp": " ジブチ",
	"dk-jp": "デンマーク",
	"vg-jp": " イギリス領ヴァージン諸島",
	"de-jp": "ドイツ",
	"ye-jp": " イエメン",
	"dz-jp": " アルジェリア",
	"us-jp": " 米国",
	"uy-jp": " ウルグアイ",
	"yt-jp": " マヨット",
	"um-jp": " 米国小離島",
	"lb-jp": "レバノン",
	"lc-jp": " セントルシア",
	"la-jp": "ラオス",
	"tv-jp": " ツバル",
	"tw-jp": "台湾",
	"tt-jp": " トリニダード・トバゴ",
	"tr-jp": "七面鳥",
	"lk-jp": " スリランカ",
	"li-jp": " リヒテンシュタイン",
	"lv-jp": " ラトビア",
	"to-jp": " トンガ",
	"lt-jp": " リトアニア",
	"lu-jp": "ルクセンブルク",
	"lr-jp": "リベリア",
	"ls-jp": " レソト",
	"th-jp": " タイ",
	"tf-jp": " フランス領南方領土",
	"tg-jp": "持ち帰り",
	"td-jp": " チャド",
	"tc-jp": " タークス・カイコス諸島",
	"ly-jp": " リビア",
	"va-jp": "バチカン",
	"vc-jp": " セントビンセントおよびグレナディーン諸島",
	"ae-jp": " アラブ首長国連邦",
	"ad-jp": " アンドラ",
	"ag-jp": " アンティグア・バーブーダ",
	"af-jp": "アフガニスタン",
	"ai-jp": " アンギラ",
	"vi-jp": " アメリカ領ヴァージン諸島",
	"is-jp": " アイスランド",
	"ir-jp": " イラン",
	"am-jp": " アルメニア",
	"al-jp": "アルバニア",
	"ao-jp": "アンゴラ",
	"aq-jp": "南極大陸",
	"as-jp": " アメリカ領サモア",
	"ar-jp": "アルゼンチン",
	"au-jp": "オーストラリア",
	"at-jp": "オーストリア",
	"aw-jp": " アルバ",
	"in-jp": "インド",
	"ax-jp": " オーランド諸島",
	"az-jp": " アゼルバイジャン",
	"ie-jp": "アイルランド",
	"id-jp": "インドネシア",
	"ua-jp": " ウクライナ",
	"qa-jp": " カタール",
	"mz-jp": "モザンビーク"
}
export default countryCodes 
