const POPULAR = [
	{"src": "barbie.png", "name": "Barbie"},
	{"src": "curious_george.png", "name": "Curious George"},
	{"src": "dokinchan.gif", "name": "Dokkinchan"},
	{"src": "donkey_kong.png", "name": "Donkey Kong"},
	{"src": "garigari.png", "name": "Garigari-kun"},
	{"src": "goku.png", "name": "Son Goku"},
	{"src": "hanakappa.png", "name": "Hanakappa"},
	{"src": "himawari.png", "name": "Himawari"},
	{"src": "jaiko.png", "name": "Jaiko"},
	{"src": "kaguyahime.png", "name": "Kaguyahime"},
	{"src": "peach.png", "name": "Princess Peach"},
	{"src": "ronald_mcdonald.png", "name": "Ronald McDonald"},
	{"src": "sazae.png", "name": "Sazae-san"},
	{"src": "sonic.png", "name": "Sonic"},
	{"src": "waldo.gif", "name": "Waldo"},
	{"src": "zelda.png", "name": "Zelda"},
	{"src": "rapunzel.png", "name": "Rapunzel"},
	{"src": "shizuka.png", "name": "Shizuka"},
	{"src": "pikachu_female.webp", "name": "Pikachu (female)"},
	{"src": "shaun_of_the_sheep.png", "name": "Shaun the Sheep"},
	{"src": "spongebob.png", "name": "Spongebob Squarepants"},
	{"src": "urashimataro.png", "name": "Urashima Taro"},
	{"src": "batman.png", "name": "Batman"},
	{"src": "porco_rosso.png", "name": "Porco Rosso"},
	{"src": "peter_pan.gif", "name": "Peter Pan"},
	{"src": "tinker_bell.png", "name": "Tinker Bell"},
	{"src": "nemo.png", "name": "Nemo"},
	{"src": "dory.png", "name": "Dory"},
	{"src": "kintaro.gif", "name": "Kintaro"},
	{"src": "jam_ojisan.gif", "name": "Uncle Jam"},
	{"src": "inkling.png", "name": "Inkling"},
	{"src": "cinderella_running.png", "name": "Cinderella"},
	{"src": "trump.png", "name": "Trump"},
	{"src": "sanae_takaichi.png", "name": "Sanae Takaichi"},
	{"src": "rufi.png", "name": "Luffy"},
	{"src": "namihei.png", "name": "Namihei"},
	{"src": "einstein.png", "name": "Einstein"},
	{"src": "kinopiko.png", "name": "Kinopiko"},
	{"src": "bowser.png", "name": "Koopa"},
	{"src": "5000_yen_lady.png", "name": "Tsuda Umeko"},
	{"src": "samus_aran.png", "name": "Samus Aran"},
	{"src": "opanchu.png", "name": "Opanchu Usagi"},
	{"src": "melonpanna.png", "name": "Melonpanna"},
	{"src": "lupin.png", "name": "Lupin III"},
	{"src": "kuromi.png", "name": "Kuromi"},
	{"src": "kirby_as_meta_knight.png", "name": "Kirby as Metanight"},
	{"src": "ohtani_shohei.png", "name": "Ohtani Shohei"},
	{"src": "miyakkii.png", "name": "Miyakki"},
	{"src": "tsukushichan.png", "name": "Tsukushi-chan"},
	{"src": "mary_had_a_little_lamb.png", "name": "Mary had a Little Lamb"},
	{"src": "kinnikuman.gif", "name": "Kinnikuman"},
	{"src": "cupid.png", "name": "Cupid"},
	{"src": "anya.png", "name": "Anya"},
	{"src": "alice.png", "name": "Alice"},
	{"src": "arare.png", "name": "Arare"},
	{"src": "ariel.png", "name": "Ariel"},
	{"src": "buzz.png", "name": "Buzz"},
	{"src": "chucky.png", "name": "Chucky"},
	{"src": "conan.png", "name": "Conan"},
	{"src": "darth_vader.png", "name": "Darth Vader"},
	{"src": "little_red_riding_hood.png", "name": "Little Red Riding Hood"}
];

export default POPULAR;
