const POPULAR = [
	{"src": "barbie.png", "name": "Barbie"},
	{"src": "curious_george.png", "name": "Curious George"},
	{"src": "dokinchan.gif", "name": "Dokkinchan"},
	{"src": "donkey_kong.png", "name": "Donkey Kong"},
	{"src": "garigari.png", "name": "Garigari-kun"},
	{"src": "goku.png", "name": "Son Goku"},
	{"src": "hanakappa.png", "name": "Hanakappa"},
	{"src": "himawari.png", "name": "Himawari"},
	{"src": "jaiko.png", "name": "Jaiko"},
	{"src": "kaguyahime.png", "name": "Kaguyahime"},
	{"src": "peach.png", "name": "Princess Peach"},
	{"src": "ronald_mcdonald.png", "name": "Ronald McDonald"},
	{"src": "sazae.png", "name": "Sazae-san"},
	{"src": "sonic.png", "name": "Sonic"},
	{"src": "waldo.gif", "name": "Waldo"},
	{"src": "zelda.png", "name": "Zelda"},
	{"src": "rapunzel.png", "name": "Rapunzel"},
	{"src": "shizuka.png", "name": "Shizuka"},
	{"src": "pikachu_female.webp", "name": "Pikachu (female)"},
	{"src": "shaun_of_the_sheep.png", "name": "Shaun the Sheep"},
	{"src": "spongebob.png", "name": "Spongebob Squarepants"},
	{"src": "urashimataro.png", "name": "Urashima Taro"},
	{"src": "batman.png", "name": "Batman"},
	{"src": "porco_rosso.png", "name": "Porco Rosso"},
	{"src": "peter_pan.gif", "name": "Peter Pan"},
	{"src": "tinker_bell.png", "name": "Tinker Bell"},
	{"src": "nemo.png", "name": "Nemo"},
	{"src": "dory.png", "name": "Dory"},
	{"src": "kintaro.gif", "name": "Kintaro"},
	{"src": "jam_ojisan.gif", "name": "Uncle Jam"},
	{"src": "inkling.png", "name": "Inkling"},
	{"src": "cinderella_running.png", "name": "Cinderella"}
];

export default POPULAR;
